// This file is generated by Slice Machine. Update with care!

// import HeroSlice from './HeroSlice';
// import ImageWithCaption from './ImageWithCaption';
import LogoList from './LogoList';
// import RowOfItems from './RowOfItems';

export {
	// HeroSlice,
	// ImageWithCaption,
	LogoList,
	// RowOfItems,
};

export const components = {
	// hero_slice: HeroSlice,
	// image_with_caption: ImageWithCaption,
	logo_list: LogoList,
	// row_of_items: RowOfItems,
};
